In [1]:
print('Die! Die! Die!')

Die! Die! Die!


In [13]:
import numpy as np
import tensorflow as tf

In [12]:
a = np.random.randint(2,6,[2,3,4])
print(a, '\n\nTranspose :\n')
print(a.transpose([1,0,2]))

[[[5 3 4 4]
  [2 3 5 3]
  [3 2 3 2]]

 [[2 2 5 3]
  [2 5 4 5]
  [5 5 4 2]]] 

Transpose :

[[[5 3 4 4]
  [2 2 5 3]]

 [[2 3 5 3]
  [2 5 4 5]]

 [[3 2 3 2]
  [5 5 4 2]]]


In [23]:
x = tf.Variable([1,2,3,4,5])
x_m = tf.math.reduce_mean(x)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [28]:
sess.run(x)

array([1, 2, 3, 4, 5], dtype=int32)

In [27]:
sess.run(x_m)

3